[package]
name = "mkcd"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Makes a directory then cd's into it"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

